### PR TITLE
Changed basics.rst to include high level details on the 5 components of Flamenco

### PR DESCRIPTION
**Pull request by binarypearl**
I'm trying to help out with Flamenco's documentation, so I re-did docs/source/user_manual/basics.rst to give a high level description of the 5 main components.  I give descriptions of what each component does, what port it listens on (if applicable), and which components you need depending on the Architecture.

I'm completely open to changing where this content goes/updates/etc, but I figured this is a good first start.  If you have any questions or comments, please let me know, thanks!

--Shaun

### CODE REVIEW

**Comment by binarypearl** [comment]
* Changed double spaces after period to single space (double spaces is what I learned in school, but doesn't matter either way to me)
* Changed all 1st person and 2nd person references to the 3rd person
* Fixed underline header issue not being long enough

Question:  I am currently using single quotes around a particular component name like 'Worker' or 'Server' to indicate that I'm referring to a specific Flamenco component.  Would it be better to use italics or nothing at all?  

Thanks for the preview page, that is much easier than running `make html` and navigating to the local page in a web browser.

--Shaun

**Comment by binarypearl** [comment]
* I removed the 'Basics' header.  Didn't feel that was offering any value
* Removed all colons ':' at the end of headers
* Changed the one header to "Flamenco components"

I did a `make html`, and it's still creating <h1></h1> tags for all of the headings.  Not sure what is going on here yet, but I found other forums of people with similar issues with reStructeredText.  

I'll take a look at the other .rst files to see what is being done.

--Shaun

**Comment by binarypearl** [comment]
I fixed the header issue.  In trying lots of different things, I originally commited a change that had all of the header markings in the same hierarchy.  Oops.

What created the confusion for me, is that I think there is a bug with:  http://rst.ninjs.org/
If you don't have any text between headers, it will display the correct <hN></hN>.  But once you start typing between them, it switches all <HN> tags to <h1></h1>.  

But I did a build and it had the hierarchy correct.

If you see anything else that you would like changed, please let me know, thanks!

--Shaun

**Comment by fsiddi** [comment]
Looks good! Thanks a lot for the patience while going through the review :)

**Comment by binarypearl** [comment]
No worries, glad I can help!  As always, feel free to request any changes to whatever I commit.  I'm more than happy to change things around.

--Shaun

**Pull request merged**
