### PR TITLE
Static storage fix

### PR DESCRIPTION
**Pull request by callym**
Allows you to change the `SERVER_STORAGE` and `MANAGER_STORAGE` config.py values to point to directories that aren't `{0}/static/storage` (as long as the dir format is still `{1}/{2}` where `{1}/missing_thumbnail.png` exists.

### CODE REVIEW

**Comment by fsiddi** [comment]
Thank you for this! I'll look at it ASAP.

**Comment by peppelinux** [comment]
This is an important commit !
See https://github.com/peppelinux/flamenco/commit/d475657df2f558d145df0c82880e81c6084796c6, I started coding it but I found this pull request from callym, so, everything will be made :)

**Comment by peppelinux** [comment]
this is an important patch !

**Comment by sybrenstuvel** [comment]
Thanks for your pull request. I'm closing this on, though, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.

**Pull request closed without merging**
